apiVersion: v1
kind: Pod
metadata:
  name: desafio-softplan
  labels:
    app: desafio-softplan
spec:
  containers:
  - name: desafio-softplan
    image: fabiosalomao/desafio-softplan-api:dev
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
